# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
      - src/stage_01_get_data.py
      - src/utils/common.py
      - configs/config.yaml
    outs:
      - data/data.xml

  prepare_data:
    cmd: python src/stage_02_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare.py
      - src/utils/common.py
      - src/utils/data_mgmt.py
      - data/data.xml
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split  
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
    cmd: python src/stage_03_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_featurization.py
      - src/utils/common.py
      - src/utils/featurize.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - configs/config.yaml
    params:
      - featurize.max_features
      - featurize.ngrams  
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_train.py
      - src/utils/common.py
      - artifacts/features/train.pkl
      - configs/config.yaml
    params:
      - train.seed
      - train.n_est  
      - train.min_split  
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/stage_05_evaluate.py --config=configs/config.yaml
    deps:
      - src/stage_05_evaluate.py
      - src/utils/common.py
      - artifacts/features/test.pkl
      - configs/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr