# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

source_data_url: https://common-data-001.s3.ap-south-1.amazonaws.com/aiops-class-demo-data/data.xml

source_download_dir:
  data_dir: data
  data_file: data.xml


plots:
  PRC: prc.json
  ROC: roc.json

metrics:
  SCORES: scores.json
