# add ci-cd steps here
name: AIOps-DVC-NLP-project

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: 'Deploy runner in EC2'
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=m \
          --labels=cml-runner 

  install-requirements-train:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: 'prepare environment, train and publish'
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

          dvc repro         

          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          dvc metrics show >> report.md

          cml-send-comment report.md
